# Docker Compose for F1 App Backend + DB + Redis

services:
  db:  # PostgreSQL database
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: f1db
      POSTGRES_USER: f1user
      POSTGRES_PASSWORD: f1usersecretpassword
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "f1user", "-d", "f1db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:  # Node.js backend
    build: ../backend
    environment:
      DATABASE_URL: postgres://f1user:f1usersecretpassword@db:5432/f1db?schema=public
      REDIS_HOST: redis          # <--- Tell backend how to reach Redis service (internal Docker network)
      REDIS_PORT: 6379           # <--- Default Redis port
      # Add other backend ENV vars here as needed (e.g., ERGAST_API_BASE)
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"

  redis:  # Redis cache
    image: redis:7-alpine
    ports:
      - "6379:6379"              # Optional: expose for local debug/inspection
    volumes:
      - redis-data:/data         # Persist Redis data for dev/demo (optional, but professional)
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  redis-data: